name: caifen

on:
  push:
    paths:
      - 'caifen/拆分表.txt'    # 指定文件：仅当推送此文件时触发
  workflow_dispatch:           # 添加手动触发器

jobs:
  handle-specific-files:
    runs-on: ubuntu-latest

    steps:
      - name: Download modules
        uses: actions/checkout@v4

      - name: Download scripts
        uses: actions/checkout@v4
        with:
          repository: mlzzz/scripts
          ref: main
          path: 092scripts
          token: ${{ secrets.MLZZZTOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: build caifen
        shell: bash
        run: |
          cp caifen/拆分表.txt 092scripts/
          cd 092scripts
          python3 ./黑体GB拆分制作/黑体串连脚本.py
          cd ..

      - name: Checkout public repository
        uses: actions/checkout@v4
        with:
          repository: mlzzz/092wb
          ref: private
          path: 092wb
          token: ${{ secrets.MLZZZTOKEN }}

      - name: Copy generated file
        run: |
          cp 092scripts/wb_spelling.dict.yaml 092wb/

      - name: Commit files
        run: |
          cd 092wb/
          git add wb_spelling.dict.yaml
          git config --local user.email "092wb@163.com"
          git config --local user.name "mlzzz"
          git commit -m "同步宋天拆分"

      - name: Push changes
        run: |
          cd 092wb
          git remote set-url origin https://${{ secrets.MLZZZTOKEN }}@github.com/mlzzz/092wb.git
          git push origin private
